### ISSUE TITLE
Improve UI indicators when logging in

### ISSUE THREAD

**Issue by domdomegg** [raisenational/raise#205]
When logging in, especially on slow network connections, the UI doesn't update to suggest to the user that they are logging in and they can continue to click the login buttons.

We should have some indicator of progress, at the very least disabling the buttons and maybe ideally a loading spinner with some text like 'Logging in...'

[screencast_00000.webm](https://user-images.githubusercontent.com/4953590/203179184-979c32ae-aa51-4a09-a357-b78ca7d5ad3e.webm)

**Comment by michaela559** [comment]
hello, can i try?

**Comment by domdomegg** [comment]
Hi @michaela559, sure! I've assigned you to this issue - let me know if anything is unclear, how you get on and if you need help :)

**Comment by michaela559** [comment]
@domdomegg sorry I have trouble building the project, when i run npm install in shared, it there are problems with postinstall/build. Do you have any idea what it means? 
<img width="225" alt="image" src="https://user-images.githubusercontent.com/115699533/203643462-0d49f9f0-b49d-4649-b68c-42b8579e2a96.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/115699533/203643486-3ac46775-4ead-47cb-b7db-aa1a45eb73d9.png">

**Comment by michaela559** [comment]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/115699533/203646928-ab6b9e13-9f01-4996-a2d9-88921b9bbb3f.png">

**Comment by domdomegg** [comment]
Hmmm, I haven't set up the project on Windows and don't have access to a Windows computer to test it with.

It looks like it's complaining about calling the postinstall script, which I think is defined in the top-level `package.json` - which itself calls the postinstall command in the workspaces. The error appears to complain that trying to do this involves running the `@raise/web` package.json's postinstall, which is: `cp -n src/env/local.template.ts src/env/local.ts && cp -n src/env/local.ts src/env/env.ts`. You can instead do this manually, by copying the file `src/env/local.template.ts` to `src/env/local.ts` and then copying `src/env/local.ts` to `src/env/env.ts`.

I think you'll likely have similar issues where we use this `cp` command elsewhere, e.g. in the server or when running `npm start`. You could temporarily modify the scripts to remove this given you're doing the copying by hand.

If you have time, maybe you can try to make this cross-platform compatible. It might look like adding some local scripts in js that use [copyFile](https://nodejs.org/api/fs.html#fspromisescopyfilesrc-dest-mode), and replacing the command with running those scripts.

**Comment by domdomegg** [comment]
Possibly installing https://www.npmjs.com/package/shx as a dev dependency, then prefixing `cp` or `rm` or `mv` commands with `shx ` might help fix this?

**Comment by domdomegg** [comment]
As this has gone stale, I'm going to reassign it to myself to complete
